### ISSUE TITLE
Use of data for OpenStreetMap

### ISSUE THREAD

**Issue by mapmeld** [cambridgegis/cambridgegis_data#6]
Hi!

I saw the addresses upload and that the addresses are now associated with building ids. OpenStreetMap is wary of importing just buildings or just addresses, but I think it would benefit from having a combined dataset. There is [documentation on OpenStreetMap's site](http://wiki.openstreetmap.org/wiki/Import/Guidelines#Make_sure_data_license_is_OK) of what data can be used, which boils down to: is the data public domain or otherwise free to reuse? Can we prove it?

OpenStreetMap already has buildings imported from MassGIS, usually without addresses: http://www.openstreetmap.org/#map=18/42.37395/-71.10329  The city's data would update the map with new and updated buildings.

Chicago used an MIT license to release buildings + addresses data; that's why our buildings are numbered: http://www.openstreetmap.org/#map=17/41.86165/-87.64667

**Comment by JesseWeinstein** [comment]
@seansweeney -- I know this is a (very) old issue, but I'm also interested in learning whether this data (particularly the street light data) could be licensed appropriately for inclusion in OSM. Any clarification you can provide would be very appreciated!

**Comment by mapmeld** [comment]
It has been a while! If it helps, Esri now has more support for sharing public data with OpenStreetMap https://www.esri.com/arcgis-blog/products/arcgis-living-atlas/mapping/arcgis-data-support-in-osm-editors/

**Comment by JesseWeinstein** [comment]
Nice -- but as I'm sure you know, that in itself doesn't help with clarifying the licensing.

**Comment by matkoniecz** [comment]
> Esri now has more support for sharing public data with OpenStreetMap https://www.esri.com/arcgis-blog/products/arcgis-living-atlas/mapping/arcgis-data-support-in-osm-editors/

That can apply to datasets owned by Esri or where Esri determined that dataset is licensed under OSM compatible license. Is either applying to this dataset?

**Comment by seansweeney** [comment]
Thank you all for checking in about data licensing for inclusion in OSM.  We are actively investigating the best approach for all of our data licenses.  If you would like to provide your input about why you think it is important that Cambridge adopt a clear and established data license for the City’s public datasets, we’d love to hear from you.  You can contact us with input about this topic by emailing us at OpenData@CambridgeMA.Gov.
