### ISSUE TITLE
Property Database

### ISSUE THREAD

**Issue by kmbrgandhi** [cambridgegis/cambridgegis_data#9]
I wanted to submit a request here regarding the Property Database csv files: at least for 2016 and 2017 (and will subsequently be checking the later files as well), there are a number of rows that are not correctly aligned (likely because a String field was mistakenly split between two columns). E.g. row 587 in the 2016 Property Database file.  This is not easily diagnosable when reading the data en masse (because sometimes this misalignment is corrected later in the row); it most often occurs with fields where PropertyClass is Private University, although not uniformly (see Row 687 in the 2017 file, where Rectory/Parsonage are similarly split).

I'm going to be working through cleaning this up for my personal use, but also wanted to ask here if this could be fixed for the base files, as that would be really helpful.

**Comment by seansweeney** [comment]
Thanks for pointing this out.  You are right, we're at least missing field delimiters for "Private College, University" entries, so they're being taken up as separate fields.

It looks like we introduced this issue in 2015 and carried it through 2019, at least for that value.

I'll work on getting these fixed.
